-- SEC: Verify remediation targets are service_role-only (read-only).
-- Authoritative catalogue: scripts/secdef-service-role-only-targets.json
-- Generated by: node scripts/verify-secdef-acl-remediation.mjs --write-sql
-- Expect: every listed function has anon=false, authenticated=false, public=false, service_role=true.
-- Target count: 53
-- Run via:
--   node scripts/verify-secdef-acl-remediation.mjs
--   npx supabase db query --linked -f scripts/verify-secdef-acl-remediation.sql -o json

with targets(regproc_text) as (
  values
    ('public._gdpr_erasure_audit(uuid,text,jsonb)'),
    ('public._gdpr_execute_erasure_action(uuid,uuid)'),
    ('public._gdpr_prepare_subject_for_auth_deletion(uuid,uuid)'),
    ('public._gdpr_remove_subject_property_links(uuid,bigint,uuid)'),
    ('public._gdpr_redact_sole_participant_property_address(bigint,uuid)'),
    ('public._gdpr_shared_transaction_safety_block(uuid,bigint,text)'),
    ('public._gdpr_action_status_on_approval(text)'),
    ('public._gdpr_compute_scope_fingerprint(jsonb)'),
    ('public.execute_property_lifecycle_action(bigint,text,text,text,uuid,jsonb)'),
    ('public.execute_property_lifecycle_archive(bigint,text,jsonb)'),
    ('public.execute_property_lifecycle_release(bigint,text,jsonb)'),
    ('public.execute_property_lifecycle_anonymise(bigint,text,jsonb)'),
    ('public.execute_enter_dormancy_warning(bigint,text,jsonb)'),
    ('public.list_property_lifecycle_worker_candidates(integer)'),
    ('public.try_acquire_property_lifecycle_lease(bigint,integer)'),
    ('public.release_property_lifecycle_lease(bigint)'),
    ('public.record_property_lifecycle_transition_worker(bigint,text,text,text,text,jsonb)'),
    ('public.persist_property_analytics_snapshot(bigint,jsonb,text)'),
    ('public.list_dormancy_warning_notification_targets(bigint)'),
    ('public.get_dormancy_warning_email_recipient(bigint)'),
    ('public.try_claim_dormancy_warning_notification(bigint,uuid,integer)'),
    ('public.mark_dormancy_warning_notification_sent(bigint,uuid,uuid)'),
    ('public.release_dormancy_warning_notification_claim(bigint)'),
    ('public.upsert_operational_summaries_service(jsonb,jsonb)'),
    ('public.list_chain_intelligence_refresh_candidates(integer)'),
    ('public._create_property_claim_invitation(bigint,uuid)'),
    ('public._revoke_open_property_claim_invitations(bigint)'),
    ('public._revoke_expired_ea_branch_invitations(uuid,text)'),
    ('public._establish_operational_homeowner_core(bigint,uuid,text,boolean)'),
    ('public._grant_counterparty_participation_core(bigint,uuid)'),
    ('public._upsert_property_membership_row(bigint,uuid,text)'),
    ('public._sync_property_claim_on_homeowner_grant(bigint,uuid)'),
    ('public._insert_participation_delink_activity(bigint,text,text)'),
    ('public._notify_chain_participants_of_delink(bigint,bigint,text)'),
    ('public._execute_participation_delink(bigint,text,uuid,text)'),
    ('public._execute_participation_delink(bigint,text,text,uuid)'),
    ('public._ea_assign_originated_property(bigint,uuid,boolean,text,text,text)'),
    ('public._create_ea_operational_property_core(bigint,text,text,text,uuid,boolean,text,text,boolean)'),
    ('public._require_verified_email_for_transaction()'),
    ('public._trg_touch_operational_activity_from_activity()'),
    ('public._trg_touch_operational_activity_from_claim()'),
    ('public._trg_touch_operational_activity_from_counterparty()'),
    ('public._trg_touch_operational_activity_from_property()'),
    ('public._gdpr_redact_billing_customer_email_dispatches(text)'),
    ('public.begin_maintenance_job_run(text,jsonb)'),
    ('public.complete_maintenance_job_run(uuid,text,integer,integer,integer,integer,jsonb,text)'),
    ('public.retain_email_events_batch(integer)'),
    ('public.preview_retain_email_events_batch(integer)'),
    ('public.retain_billing_email_dispatches_batch(integer)'),
    ('public.preview_retain_billing_email_dispatches_batch(integer)'),
    ('public.retain_invitation_pii_batch(integer)'),
    ('public.preview_retain_invitation_pii_batch(integer)'),
    ('public.trg_enforce_structured_activity_update()')
),
resolved as (
  select
    t.regproc_text as function,
    to_regprocedure(t.regproc_text) as oid
  from targets t
)
select
  r.function,
  case when r.oid is null then null else has_function_privilege('anon', r.oid, 'EXECUTE') end as anon,
  case when r.oid is null then null else has_function_privilege('authenticated', r.oid, 'EXECUTE') end as authenticated,
  case when r.oid is null then null else has_function_privilege('service_role', r.oid, 'EXECUTE') end as service_role,
  case when r.oid is null then null else has_function_privilege('public', r.oid, 'EXECUTE') end as public_execute,
  case
    when r.oid is null then 'FAIL_MISSING'
    when has_function_privilege('anon', r.oid, 'EXECUTE') then 'FAIL'
    when has_function_privilege('authenticated', r.oid, 'EXECUTE') then 'FAIL'
    when has_function_privilege('public', r.oid, 'EXECUTE') then 'FAIL'
    when not has_function_privilege('service_role', r.oid, 'EXECUTE') then 'FAIL'
    else 'PASS'
  end as status
from resolved r
order by r.function;
